### ISSUE TITLE
Error Missing assets

### ISSUE THREAD

**Issue by Mellanie1992** [TobbyTheBobby/TimberbornModsUnity#2]
My best guess as complete noob at coding, Is that the problem is at not locating the right folder locations ?

HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Ladder.Plugin.Awake () (at C:/Users/Tobbert/SynologyDrive/Unity Projecten/TimberbornModsUnity/Assets/Ladder/Plugin.cs:27)

[Missing Assets.txt](https://github.com/TobbyTheBobby/TimberbornModsUnity/files/9333694/Missing.Assets.txt)

PS:
I am using the Thunderstore mod launcher and the GOG version of the game.
(Or in my own blame i am using the latest version that is not on experimental, And my report is Invalid in that case my sincerest appologies)

[Edit:] I just see it might be an Timber API issue, Appologies if that is what created the actual issue.

```
[Error  : TimberAPI] Failed to load assets for prefix: tobbert.ladder
[Error  : TimberAPI] Could not find a part of the path 'C:\Users\mmwen\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Timberborn\profiles\1\BepInEx\plugins\Tobbert-Ladder\assets'.
```

**Comment by TobbyTheBobby** [comment]
Sorry that I haven't responded earlier, I didn't get a notification. 
The error is from code that shouldn't exist at all in the package. Are you trying to setup a environment?

**Comment by TobbyTheBobby** [comment]
Aaah, yes, you have to be on experimental. The latest TimberAPI only works on experimental. Check the offical discord for compatebility of mods.

**Comment by Mellanie1992** [comment]
Sorry for my late reply aswell Enviornment ? 
No but i may have launched it when somehow an incomplete version was loaded/corrupted by the Mod manager,
As it was fixed as soon as i deleted the folder (Because it was missing parts compared to manual installation of the mod)
