### ISSUE TITLE
[Suggestion] More Paths Corner Fill

### ISSUE THREAD

**Issue by VasVadum** [TobbyTheBobby/TimberbornModsUnity#5]
I noticed in your screenshots of the mod, that the corners for paths when boxed in, are still ground. I was wondering if you could find some way to fill in the  corners so that if you for example, have a square of path or a 2x wide path for some reason, that the paths corners will get filled in and it won't look like you have a bunch of holes in your path.

Here's an example.
![image](https://user-images.githubusercontent.com/1490797/189978095-aac0b6fa-49d4-4841-9d68-236e266b17e2.png)

**Comment by TobbyTheBobby** [comment]
For sure something I would love to get working, so keeping this open. But this could be hard, because of how paths work. Will keep this updated!

**Comment by VasVadum** [comment]
Is it also at all possible to allow paths to be placed on paths to replace them? So I don't have to pick up every path, in order to swap them out?

**Comment by TobbyTheBobby** [comment]
Yes, that is also something I want to work on.

**Comment by TobbyTheBobby** [comment]
As I think your second comment is better suited for a separated mod, I close this issue as it was added since the latest release of MorePaths.

**Comment by VasVadum** [comment]
How is placing paths over paths related to a separate mod? :P Its simply swapping paths out. But alright then.

**Comment by TobbyTheBobby** [comment]
Because if i were to make it, then it would be a mod that replaces any building with any other building or specify which builds can replace certain buildings. As making it just for paths would take as long because of how the game works.

**Comment by VasVadum** [comment]
Ah, alright. Well it would be a good mod hook then, if you made a mod library for people to use that would let them specify building swap types and whatnot. But anyway, thats just my one annoyance with the paths is that I have to pick them all up and the mass pickup feature, doesn't let you do that for just paths, it'll do it for everything that touches the paths or is above the path. :P
