### ISSUE TITLE
problem with Global market

### ISSUE THREAD

**Issue by klaper10git** [TobbyTheBobby/TimberbornModsUnity#9]
I encountered two problems with the global market.
1. main menu shows items multiplied by number of placed global markets ( showed stored planks = 1000  real planks in storage=>400-> 100(in vanila warehouse+3(global markets)* 300 stored in shared space) .
 2. more serious: beavers do not take supplies from global market unless i disallow good(s) from storage and enable again. however it doesn't apply to water and feed. i have tried running it without other types storages but it did not help. deleting all storages also made no changes. also clean save did not helped and max storage limit made no progress.

**Comment by TobbyTheBobby** [comment]
As global market for now is discontinued and the mechanics will probably change, I will close this issue.
